### ISSUE TITLE
removeEventListener

### ISSUE THREAD

**Issue by jcemer** [ccampbell/gator#1]
Hi!

Why you never removeEventListener? I'm  read the code and think they should accumulate a lot of listener in same element with something like:

``` javascript
var gator = new Gator(document);
gator.on('mousedown');
gator.off('mousedown');
gator.on('mousedown');
...
```

Is this ok?

**Comment by shimscharf** [comment]
I respectfully disagree,

Leaving actual listeners attached to the nodes / elements does cause a memory leak, which although is cleared correctly in modern browsers, it still remains an issue in IE6 - IE8.

All event listeners should be deregistered using removeEventListener / detachEvent.
